sudo: required

services:
  - docker

language: go

go:
  - 1.6.2

script:
  - make
  - make collect-cover-data
  - make test-cover-html
  - make test-cover-func

after_success:
  - bash <(curl -s https://codecov.io/bash)
