sudo: required

services:
  - docker

language: go

go:
  - 1.6.2

script:
  - docker run -i --rm -w /go/src/github.com/Dataman-Cloud/swan -v $(pwd):/go/src/github.com/Dataman-Cloud/swan golang:1.6.2 make
  - docker run -i --rm -w /go/src/github.com/Dataman-Cloud/swan -v $(pwd):/go/src/github.com/Dataman-Cloud/swan golang:1.6.2 make collect-cover-data
  - docker run -i --rm -w /go/src/github.com/Dataman-Cloud/swan -v $(pwd):/go/src/github.com/Dataman-Cloud/swan golang:1.6.2 make test-cover-html
  - docker run -i --rm -w /go/src/github.com/Dataman-Cloud/swan -v $(pwd):/go/src/github.com/Dataman-Cloud/swan golang:1.6.2 make test-cover-func

after_success:
  - bash <(curl -s https://codecov.io/bash)
