sudo: required

services:
  - docker

language: go

go:
  - 1.8.1

script:
  - make
  - make collect-cover-data
  - make test-cover-html
  - make test-cover-func
  - make integration-test

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
  
notifications:
   webhooks: https://oapi.dingtalk.com/robot/send?access_token=097145956683f97d99854f5287482f1c5520fffd7be65c986e43e70c481f6322
